# MTG Agent Benchmark Configuration
# Copy this file to config.yaml and update with your actual values

openrouter:
  api_key: "your_openrouter_api_key_here"

agents:
  agent1:
    name: "GPT-5 mini"
    model: "openai/gpt-5-mini"
  agent2:
    name: "Claude"
    model: "anthropic/claude-4-sonnet"

draftsim:
  base_url: "https://draftsim.com"
  draft_url: "https://draftsim.com/draft.php?mode=Sealed_EOE"
